Cabecera
sebaspani93/Hyperblogp pull request #3
Opened 2023-01-27 22:05 UTC by sebaspani93

create of PR for new test

2023-01-27 22:12 UTC, gdavidvm193 requested changes

2023-01-27 22:12 UTC, gdavidvm193 commented on .gitignore
> +*.jpg
porque solo jpg?

2023-01-27 22:12 UTC, gdavidvm193 commented on Blog.html
>      <div id="contenedor">
todo en ingles

2023-01-27 22:12 UTC, gdavidvm193 commented on Blog.html
> +        <div id="cabecera">
todo en ingles

2023-01-27 22:12 UTC, gdavidvm193 commented on Blog.html
> +            <img id="logo" src="imagenes/icoweb.svg" >
todo en ingles

2023-01-27 22:12 UTC, gdavidvm193 commented on Blog.html
> +            <span id="tagline">Bienvenidos al nuevo HyperblogP</span>
use camelCase

2023-01-27 22:12 UTC, gdavidvm193 commented on Blog.html
> +            <p><img id="sofia" src="imagenes/sofia.jpg"></p>
todo en ingles

2023-01-27 22:12 UTC, gdavidvm193 commented on Blog.html
> +            <p id="parrafomaster">Este otro parrafo lo voy a utilizar para unos cambios de letra y si es posible de una vez de color, para modificar el master
todo en ingles

2023-01-27 22:12 UTC, gdavidvm193 commented on README.md
> +# Hyperblogp
mejore el Readme busque ejemplos

2023-01-27 22:12 UTC, gdavidvm193 commented on css/estilo.css
> +    padding: 1em;
expliqueme las diferentes medidasy porq em

2023-01-27 22:12 UTC, gdavidvm193 commented on css/estilo.css
>      color: blue;
prohibido usar estos colores, solo rgb o hex

2023-01-30 15:28 UTC, sebaspani93 commented
Creo que ya hice todos los cambios necesarios para aprobarlo

2023-01-30 16:29 UTC, gdavidvm193 requested changes

2023-01-30 16:29 UTC, gdavidvm193 commented on Blog.html
> +            <img id="logo" src="imagenes/icoweb.svg" >
Falta las carpetas

2023-01-30 16:40 UTC, gdavidvm193 requested changes

2023-01-30 16:40 UTC, gdavidvm193 commented on css/style.css
> +    padding: 1em;
Cuales son las unidades de medida, póngalas todas en un comentario y expliquelas

2023-01-30 17:02 UTC, gdavidvm193 commented on css/style.css
> +    padding: 1em;
@sebaspani93

2023-01-30 19:21 UTC, gdavidvm193 approved these changes

2023-01-30 19:21 UTC, merged